### ISSUE TITLE
Create test script that checks the kernel for prerequisites

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#34]
To ease porting it is necessary to check the kernel

**Comment by pclesr** [comment]
I completely forgot about checking this in . Where should it go?

**Comment by flxo** [comment]
@pclesr I'd say: put it to the root and add a hint in `Configuring and Running Northstar` in the README? What do you think?

**Comment by pclesr** [comment]
I will update the 'Configuring...', but I'd rather not put it in the root. How about making a 'contrib' directory ? Many projects have something like that where people can put contributions that are not directly related to the source code.

**Comment by flxo** [comment]
Hm. By suggesting to put it to the root I tried to avoid that we need to find a name - or even better - not have such a dump dir anywhere ;-)

`contrib` sometimes means that it's content is unmaintained and this is not the case here.

**Comment by pclesr** [comment]
I really don't want to clutter the root with something like this -- it is only used as a helper for configuring and really is not important in the day-to-day running and compiling of north.

Maybe a tools dir, or a subdirectory of the doc directory, since it is basically an extension of the documentation ? What I mean is that this script is just a helper for what is already in the documentation regarding the required kernel config params.

**Comment by flxo** [comment]
@pclesr your choice ;-)

**Comment by flxo** [comment]
Fixed with #107
