### ISSUE TITLE
ESR-01-012 WP1: Lax identity binding of authentication tokens (Info)

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#794]
While reviewing the design of the authentication token API in northstar-0.6.0, it was noticed that tokens created by the runtime are not tightly coupled with the sender of the token. More specifically, the verifier of a token cannot determine if the sender is also the creator and owner of this token.
The Northstar runtime supports creating and verifying authentication tokens. Each token created by the runtime is constructed from:
• Target container name (supplied by caller)
• Shared data (supplied by caller)
• Creating container name (supplied by runtime)
• Creation time (supplied by runtime)
• Validity duration (supplied by runtime)
For verification, the token itself, in combination with the shared data and the creation of the container name, are handed to the runtime by the verifying container. The target container name here is supplied by the runtime (i.e., it is the calling container’s name). Thus, a token is only valid if the caller of the verification call matches the target container’s name, as it was used to create the token.
Since the verifier of a token has to rely on the sender of the token to supply the name that was used to create the container token, the sender has full control over this item. As a result, there is only a loose binding of a token to its sender. While a compromised container with access to the token console API can create new tokens for exclusive use, it is still possible to obtain other containers’ tokens and use them.
As Northstar does put all containers into the (host) network namespace by default, this increases the chances of obtaining another container’s token. One example might be the use of the SO_REUSEPORT socket option, which would allow a malicious container to listen to the same port as the legitimate container receiving the tokens.

**Comment by inorick** [comment]
> Since the verifier of a token has to rely on the sender of the token to supply the name that was used to create the container token, the sender has full control over this item.

Who is providing the sender's container name during token verification? Is it provided by the token sender and the target container that wants to verify the token just forwards it?

**Comment by flxo** [comment]
The target container just forwards the name but the name is also part of the token right?

**Comment by inorick** [comment]
Yes, I think what they mean is that if an attacker compromises container A, obtains tokens from container B and can chose which name is used during verification, he can connect from container A to some target container and claim to be B. If we encode something else into the tokens that cannot be chosen by an attacker when connecting to a target, then the stolen tokens would not be usable that way.

**Comment by flxo** [comment]
@inorick How do we continue here? As far as I get it this issue cannot be solved by Northstar because it must be supported by the protocol/transport mechanism in use e.g unix socket credentials.

**Comment by inorick** [comment]
Agreed. The problem is that the token is tied to its creator and not to the sender of a particular connection. To achieve this, we would need a way for the target container to ask the runtime: "What container is this connection really originating from". Then it could use that information and compare it to the claimed identity of the sender. I do not think that there is anything we could add to a token to tie to a connection (like an IP address) that could not be spoofed by an attacker.

As a side note, I do not think that this problem would go away if we used a full blown PKI. An attacker that obtains the private key of one container can use it to impersonate that container from another container.

**Comment by inorick** [comment]
I think we can close this as I do not see any unspoofable connection identifier that we could tie to the tokens.

**Comment by flxo** [comment]
@inorick Agree. This can only be fixed with support from the protocol or transport used. The runtime cannot.

**Comment by 1ohn-Brown1** [comment]
To the people who stole and renamed MY code and MY encryption from ÆTHOR to the multiple different things you call it now....the real author [TH] is coming for you! And soon you'll see just how automagically all my identifiers are restored when I take the hard copy proof I have of your theft to court! I bet you never did find the master LOL....PG 105 is altered because of a fail safe I programmed in that printed a specific word and picture  upon the theft and alterations of my my proprietary property. MRÆ is me CI McGee. You should have checked the FIG! Ccc u sn

**Comment by flxo** [comment]
wow. Github spam...
